### ISSUE TITLE
Get Account ID

### ISSUE THREAD

**Issue by mamoyko** [mamoyko/CRM#1]
```
router.post('/convert_account', function(req,res){
	var obj = {};
	var account_name = req.body.account_name;
	var account_owner = req.body.account_owner;
	var lead_source = req.body.lead_source;
	var industry = req.body.industry;
	var website = req.body.website;
	var number_of_employees = req.body.number_of_employees;
	var address = req.body.address;
	var city = req.body.city;
	var country = req.body.country;
	var phone_number = req.body.phone;
	var lead_id = req.body.leads_id;
	var lead_status = '5';
	var errors = req.validationErrors();
	console.log(req.body);
	if (errors) {
		console.log('errors');
	} else {
		Leads.findByIdAndUpdate({
			_id:lead_id
		},
			{ 
				$set: 
					{ 
						lead_status : lead_status
					 },

			},
			{ upsert: false, new: true },
			function(err, newLead){
				if (err) {
					console.log("errors tanga");
				} else {
					// res.end("success");
					console.log("--------------- success lead -------------------");
				}
		});
	}

	if (errors) {
		console.log('errors');
	} else {
		var newAccount = new Account({
			account_name : account_name,
			account_owner : account_owner,
			lead_source : lead_source,
			industry : industry,
			website : website,
			number_of_employees : number_of_employees,
			address : address,
			city : city,
			country : country,
			phone_number : phone_number

		});
		Account.createAccount(newAccount,{upsert : false, new:true}, function(err,account){
			if (err) {
				res.json(err);
			} else {
				console.log("--------------- success Account -------------------");
				console.log(account) //need to get this new account id;
			}
			console.log(account);
		});
	}

	res.send('success');

});
```

**Comment by h0m36r0wn** [comment]
``router.post('/convert_account', function(req,res){
	var account_name = req.body.account_name;
	var account_owner = req.body.account_owner;
	var lead_source = req.body.lead_source;
	var industry = req.body.industry;
	var website = req.body.website;
	var number_of_employees = req.body.number_of_employees;
	var address = req.body.address;
	var city = req.body.city;
	var country = req.body.country;
	var phone_number = req.body.phone;
	var lead_id = req.body.leads_id;
	var lead_status = '5';
	var errors = req.validationErrors();

	//Update data
	var updatedLead  = { lead_id: lead_id};

	//New account data 
	var newAccount = { account_name : account_name, account_owner : account_owner,lead_source : lead_source,
		industry : industry,website : website,number_of_employees : number_of_employees,
		address : address,city : city,country : country,phone_number : phone_number
	};

	updateLead(updateLead,function(err, updatedObj){
		if(err) res.send(err);
		if(updatedObj){
			createAccount(newAccount, function(err, newAccountObj){
				if(err) res.send(err);
				if(newAccountObj) res.send('success');
			})
		}
	})

});

/*
 *Update Leads
 *@param Object data { lead_id, leadStatus}
 * @return Callback 
*/
function updateLead(data, cb){
	var query = { "_id":lead_id };
	var updates = { "$set": { "lead_status":data.leadStatus } };
	var opts = { "upsert":false, "new":true };
	Leads.findOneAndUpdate(query, updates, opts, function(err, leadObj){
		if(err) callback('Unknown error happend', null); // return callback with error message
		if(leadObj) callback(null, leadObj); //return a callback with update Leads info
	})
}

/*
 *Update Leads
 *@param Object new account object { account_name ... }
 * @return Callback 
*/

function createAccount(newAccount, cb){
	Account.createAccount(newAccount, function(err, accountObj) {
		if(err) callback('Unknown error happened while creating account', null);
		if(accountObj) callback(null, accountObj);
	})
}

**Comment by h0m36r0wn** [comment]
``router.post('/convert_account', function(req,res){
	var account_name = req.body.account_name;
	var account_owner = req.body.account_owner;
	var lead_source = req.body.lead_source;
	var industry = req.body.industry;
	var website = req.body.website;
	var number_of_employees = req.body.number_of_employees;
	var address = req.body.address;
	var city = req.body.city;
	var country = req.body.country;
	var phone_number = req.body.phone;
	var lead_id = req.body.leads_id;
	var lead_status = '5';
	var errors = req.validationErrors();

	//Update data
	var updatedLead  = { lead_id: lead_id};

	//New account data 
	var newAccount = { account_name : account_name, account_owner : account_owner,lead_source : lead_source,
		industry : industry,website : website,number_of_employees : number_of_employees,
		address : address,city : city,country : country,phone_number : phone_number
	};

	updateLead(updateLead,function(err, updatedObj){
		if(err) res.send(err);
		if(updatedObj){
			createAccount(newAccount, function(err, newAccountObj){
				if(err) res.send(err);
				if(newAccountObj) res.send('success');
			})
		}
	})

});

/*
 *Update Leads
 *@param Object data { lead_id, leadStatus}
 * @return Callback 
*/
function updateLead(data, cb){
	var query = { "_id":lead_id };
	var updates = { "$set": { "lead_status":data.leadStatus } };
	var opts = { "upsert":false, "new":true };
	Leads.findOneAndUpdate(query, updates, opts, function(err, leadObj){
		if(err) callback('Unknown error happend', null); // return callback with error message
		if(leadObj) callback(null, leadObj); //return a callback with update Leads info
	})
}

/*
 *Update Leads
 *@param Object new account object { account_name ... }
 * @return Callback 
*/

function createAccount(newAccount, cb){
	Account.createAccount(newAccount, function(err, accountObj) {
		if(err) callback('Unknown error happened while creating account', null);
		if(accountObj) callback(null, accountObj);
	})
}

**Comment by h0m36r0wn** [comment]
router.post('/convert_account', function(req,res){
	var account_name = req.body.account_name;
	var account_owner = req.body.account_owner;
	var lead_source = req.body.lead_source;
	var industry = req.body.industry;
	var website = req.body.website;
	var number_of_employees = req.body.number_of_employees;
	var address = req.body.address;
	var city = req.body.city;
	var country = req.body.country;
	var phone_number = req.body.phone;
	var lead_id = req.body.leads_id;
	var lead_status = '5';
	var errors = req.validationErrors();

	//Update data
	var updatedLead  = { lead_id: lead_id};

	//New account data 
	var newAccount = { account_name : account_name, account_owner : account_owner,lead_source : lead_source,
		industry : industry,website : website,number_of_employees : number_of_employees,
		address : address,city : city,country : country,phone_number : phone_number
	};

	updateLead(updateLead,function(err, updatedObj){
		if(err) res.send(err);
		if(updatedObj){
			createAccount(newAccount, function(err, newAccountObj){
				if(err) res.send(err);
				if(newAccountObj) res.send('success');
			})
		}
	})

});

/*
 *Update Leads
 *@param Object data { lead_id, leadStatus}
 * @return Callback 
*/
function updateLead(data, cb){
	var query = { "_id":lead_id };
	var updates = { "$set": { "lead_status":data.leadStatus } };
	var opts = { "upsert":false, "new":true };
	Leads.findOneAndUpdate(query, updates, opts, function(err, leadObj){
		if(err) callback('Unknown error happend', null); // return callback with error message
		if(leadObj) callback(null, leadObj); //return a callback with update Leads info
	})
}

/*
 *Update Leads
 *@param Object new account object { account_name ... }
 * @return Callback 
*/

function createAccount(newAccount, cb){
	Account.createAccount(newAccount, function(err, accountObj) {
		if(err) callback('Unknown error happened while creating account', null);
		if(accountObj) callback(null, accountObj);
	})
}
